/**
Problem 2
	Even Fibonacci numbers
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting 
    with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the 
    sum of the even-valued terms.
**/

var currNum = 1;
var prevNum = 0;
var sum = 0;

while (currNum < 4000000) {
    var tempSum = currNum + prevNum;
    if (tempSum % 2 === 0) {
        sum += tempSum;
    }
    prevNum = currNum;
    currNum = tempSum;
}

console.log("The sum of the even values of the Fibonacci sequence, whose values do not exceed four million, is " 
    + sum + ".");